### ISSUE TITLE
"horsey" is not a suitable alternative to jQueryUI autocomplete

### ISSUE THREAD

**Issue by karlgroves** [davidyezsetz/you-might-not-need-jquery-plugins#15]
Believe me, I get the point about not needing jQuery/ not needing jQuery plugins. But there's something really important to keep in mind.  Many of the more mature jQuery plugins out there - particularly jQueryUI widgets - have much better accessibility than some of these "alternatives".  For instance, the jQueryUI autocomplete is hands-down the most accessible autocomplete I've come across. The behavior of jQueryUI autocomplete even surpasses most native desktop software.

**Comment by voxpelli** [comment]
Perhaps this can be solved by adding a field for `shortcomings` or just plainly `comments` where things one sacrifices can be pointed out? A bit like how CanIUse.com points out partial support for features within browsers.

Often newer libraries have worse accessibility, but it can change over time as the adoption increases and contributions and collaboration starts to pick up speed. So I think libraries with shortcomings like this should still be included, but that it should be highlighted that one may make a sacrifice by moving to it.

**Comment by davidyezsetz** [comment]
@karlgroves I completely agree. jQuery and jQuery UI is fantastic software, especially because it's as mature as it is. However you have to give younger libraries a chance to get there. I noted at the bottom of the page (I probably should move this up) that the plugins are not a 1 to 1 replacement, but offer similiar functionality.
I really like the idea of @voxpelli to point out exactly what you're missing so you can make a better decision on wether or not a plugin suits your needs.
The only problem with this is that it requires a much more in-depth testing of the plugings for which I currently don't have the time.
I will however create an issue to include a comment section where this information will reside in the future. I'll probably won't get around to do it before October, but maybe someone files a Pullrequest in the meantime. => https://github.com/davidyezsetz/you-might-not-need-jquery-plugins/issues/16

**Comment by davidyezsetz** [comment]
Closing this now. @karlgroves if you disagree that #16 is a solution to this problem I'd reopen.
